config/routes.rb
Tickets::Application.routes.draw do
  resources :tickets

  root :to => 'tickets#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :email, :number, :reporter, :ticket_status_id, :user_id, :content

  belongs_to :ticket_status
  belongs_to :user
  has_many :ticket_responses

  validates_uniqueness_of :number

  validates_presence_of :email, :number, :reporter, :ticket_status, :content

  validates :email, :email => true

  before_validation lambda{
    self.ticket_status ||= TicketStatus.default
    self.number = self.class.get_last_number.next
  }

  def self.get_last_number
    order("`number` DESC").limit(1).first.number
  rescue
    "AA-000000"
  end
end

app/models/ticket_response.rb
class TicketResponse < ActiveRecord::Base
  attr_accessible :content, :ticked_id, :user_id

  belongs_to :ticket
  belongs_to :user

  validates_presence_of :content
  validates_presence_of :ticket
  validates_presence_of :user
end

app/models/ticket_status.rb
class TicketStatus < ActiveRecord::Base
  attr_accessible :code, :name

  has_many :tickets

  validates_presence_of :code, :name
  validates_uniqueness_of :code

  def self.default
    self.get_status(:waiting_for_staff_response)
  end

  def self.get_status status = nil
    where(:code => status).limit(1).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :login, :name, :surname

  has_many :ticket_responses
  has_many :tickets

  validates :email, :presence => true, :email => true
  validates_presence_of :login
  validates_presence_of :name
  validates_presence_of :surname

  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tickets
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield

app/views/tickets/_error.html.haml
-if ticket.errors.any?
  #error_explanation
    %h2= "#{pluralize(ticket.errors.count, "error")} prohibited this ticket from being saved:"
    %ul
      - @ticket.errors.full_messages.each do |msg|
        %li= msg

app/views/tickets/edit.html.haml
%h1 Editing ticket

= form_for @ticket do |f|
  = render :partial => "error", :locals => {:ticket => @ticket}
  %h2= f.label "Reporter:"
  = f.text_field :reporter
  %h2= f.label "Email:"
  = f.text_field :email
  %h3= f.label "Content:"
  = f.text_area :content
  %h3= f.label "Status:"
  = select("ticket", "ticket_status_id", TicketStatus.all.collect {|t| [ t.name, t.id ] })

  .actions
    = f.submit 'Save'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
%h1 Listing Tickets

%table
  %tr
    %th= "Number"
    %th= "Reporter"
    %th= "Email"
    %th= "Status"
    %th
    %th
    %th

  - @tickets.each do |ticket|
    - unless ticket.blank?
      %tr
        %td= ticket.number
        %td= ticket.reporter
        %td= ticket.email
        %td= ticket.ticket_status.name
        %td
          = link_to 'Show', ticket
          = link_to 'Edit', edit_ticket_path(ticket)
          = link_to 'Destroy', ticket, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Article', new_ticket_path

app/views/tickets/new.html.haml
%h1 New article

= form_for @ticket do |f|
  = render :partial => "error", :locals => {:ticket => @ticket}
  %h2= f.label "Reporter:"
  = f.text_field :reporter
  %h2= f.label "Email:"
  = f.text_field :email
  %h3= f.label "Content:"
  = f.text_area :content

  .actions
    = f.submit 'Save'

= link_to 'Back', tickets_path

app/views/tickets/show.html.haml
%p#notice= notice

%h2= @ticket.number
%h2= @ticket.reporter
%h2= @ticket.email
%h2= @ticket.ticket_status.name
%h3= @ticket.content

= link_to 'Edit', edit_ticket_path(@ticket)
\|
= link_to 'Back', tickets_path